name: static analysis
on: [pull_request]
jobs:
    phpstan:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: PHPStan
              uses: docker://oskarstark/phpstan-ga
              with:
                  args: analyse
